[package]
name = "beanstalk"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
fs_extra = "1.3.0"
regex = "1.10.4"
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
tokio = { version = "1.37", features = ["full"] }
tokio-stream = "0.1.15"
warp = "0.3.7"