[navbar]

[main:

0. Don't take ethical codes too seriously
1. Don't take yourself too seriously
2. Don't take life too seriously
4. Your lists should not be repetitive
5. Your lists should not be repetitive
6. Your lists should not be repetitive
7. Empathy, or at least the pursuit of understanding the internal world of others, is the first and most important step in figuring out how to better the world around you.