-- Beanstalk example!
variable := "variables"
float_constant :: 5 * 68.9
beans_img : "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Heinz_Beanz.jpg/2560px-Heinz_Beanz.jpg"
---
# Beanstalk looks a bit like markdown
But all of a sudden you can start using *scenes*.

[rgb(140, 200, 255): Scenes are a way to group and style sections of your content. They can easily import [variable], and can contain expressions. And it's all [ 60 + 40 ]% clean, concise and readable.]

## Why use Beanstalk?
- You can write your content naturally, without any HTML or CSS boilerplate.
- Break out into using powerful compiled expressions anytime
- Modern programming language syntax and modern UI sensibilities all in one file.

You can easily add variables into your scenes such as that float defined earlier ([float_constant]). And all of this content automatically gets wrapped in the approrpriate HTML tags and CSS classes.

# Cool Things
You can easily add images, videos, and other media to your content, and even add multiple within the same scenehead for them to automatically be placed in a grid.

[
   img beans_img, alt "BEANS",
   img beans_img, alt "BEANS",
   img beans_img, alt "BEANS",
   img beans_img, alt "BEANS",
]