#project [
    name: "html_project",
    version: "0.1.0",
    description: "",
    main: "src/home.bs",
    author: "",
    license: "MIT"
]

#config [
    title: "Website Title",
    description: "Website Description",
    url: "localhost:3069",
    locale: "en_US",
    page_type: "website",
    favicons: "./dist/images/favicons",
    default_image: "./dist/images/default.png",
    page_x_large_image: "./dist/images/x_default.jpg"
]