#title "Test File"
#date "2024-2-4"
---
# Heading
some text content that is basically markdown.

## Subheading
More text content that is basically markdown. But this time we've got an inline element {: wooo inline text, should be wrapped in a span}. Followed by a div element.

{: This should be inside a div or just a new p tag. TO DO! }

This paragraph has a single newline in the middle of it right here
and this next now should be in the same paragraph.

### H3 heading
underscores should make a horizontal line. Like this:
____________________________________________________

#### Dotted Underline
................

#### Normal Underline
----------------

Underlining is only for headings.


